### ISSUE TITLE
Resource pack fails to load.

### ISSUE THREAD

**Issue by LevelWilson** [BalintCsala/VanillaPuddingTart#10]
I'm not sure if I set it up correctly but when I put on the resource pack and put on fabulous, minecraft tells me it failed to load. I am on a macbook pro 2020 model m1 if that helps.

**Comment by BalintCsala** [comment]
Post latest.log from the logs folder inside the minecraft folder, but there's a high likelyhood it's just M1 being M1. There's a warning when you turn on the Faboulous graphics mode for a reason

**Comment by OrangeCatUnderscore** [comment]
I have the same issue, but different hardware.. I am using an AMD RX 6700 XT on Linux
[2022-08-04-2.log](https://github.com/BalintCsala/VanillaPuddingTart/files/9261837/2022-08-04-2.log)

**Comment by BalintCsala** [comment]
@OrangeCatSeth You didn't install it correctly
![image](https://user-images.githubusercontent.com/33815391/182916912-7ed7356d-69bf-4842-94e6-7fb6351099b9.png)
