### ISSUE TITLE
Broken rendering after auto install, both on linux & windows

### ISSUE THREAD

**Issue by Dmeerev** [BalintCsala/VanillaPuddingTart#11]
![изображение](https://user-images.githubusercontent.com/51266449/181741315-dd9ca438-35cb-4490-a298-8fc24d782621.png)

**Comment by BalintCsala** [comment]
![image](https://user-images.githubusercontent.com/33815391/181745359-4b12c597-b6ab-4f40-8872-685de20b5db1.png)
