### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by langamer99** [BalintCsala/VanillaPuddingTart#12]
when i load a world it blacks out the sceen, but if i move around i can see light being reflected off the item i am holding. my hardware is Win11 64bit on amd r7 360 2gb vram, intel i3 6100D, 16gb ram

**Comment by BalintCsala** [comment]
What's your screen resolution and game version?

**Comment by langamer99** [comment]
1920x1080, 1.17.1 but tried it on other versions

**Comment by BalintCsala** [comment]
As this was with an older version, I'll close this issue.
