### ISSUE TITLE
Im so stupid sorry

### ISSUE THREAD

**Issue by Sanya268** [BalintCsala/VanillaPuddingTart#13]
I trying to install this cool resource pack but I failed around 10 times
It always says resource pack fails to load
I trying to do this on AMD RX 470 and 1.19.2 Minecraft
What can I do?
Maybe you have already created resource packs for testing on my PC?

**Comment by BalintCsala** [comment]
Post your logs please

**Comment by Sanya268** [comment]
[latest.log](https://github.com/BalintCsala/VanillaPuddingTart/files/9541636/latest.log)

**Comment by BalintCsala** [comment]
Fixed the issue, please redownload the shader

**Comment by Sanya268** [comment]
I redownloaded the shader from releases and rebuild resource pack and it doesn't work again
[latest.log](https://github.com/BalintCsala/VanillaPuddingTart/files/9542098/latest.log)

**Comment by BalintCsala** [comment]
@Sanya268 
![image](https://user-images.githubusercontent.com/33815391/189525950-afc774cf-61d9-4528-9a57-eb2638d7b8a4.png)

**Comment by Sanya268** [comment]
Thanks now it works!
