### ISSUE TITLE
Something is wrong with textures

### ISSUE THREAD

**Issue by Jiigaw** [BalintCsala/VanillaPuddingTart#15]
**Description of the bug**
The textures are messed up and the shader wont work. Then it turns off fabulous and swiches off the recourcepack.
Here is what i found about it:

- [13:38:17] [Render thread/WARN]: Shader counter could not find uniform named OutSize in the specified shader program.
- [13:38:17] [Render thread/WARN]: Shader water could not find uniform named ProjMat in the specified shader program.
- [13:38:17] [Render thread/WARN]: Shader path_tracer could not find uniform named ProjMat in the specified shader program.
- [13:38:17] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
- net.minecraft.class_761$class_5347: Failed to load shader: minecraft:shaders/post/transparency.json

**Resourcepack in use**
Just fabric mods(required to launch minecraft fabric)

**System information**
The specs of your computer, example:
GPU: Nvidia GTX 960M
CPU: IN i7-6700HQ
OS: Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/102327832/205050893-1110cfd9-68d9-471f-8119-82b5a4490265.png)
![image](https://user-images.githubusercontent.com/102327832/205053982-88f51652-2f97-4b70-8077-c9f4a7f1ebe0.png)

**Comment by Jiigaw** [comment]
[latest.log](https://github.com/BalintCsala/VanillaPuddingTart/files/10132450/latest.log)
I forgot to add the log, sorry

**Comment by BalintCsala** [comment]
The shader doesn't work with sodium

**Comment by Jiigaw** [comment]
Oh, thanks!
