### ISSUE TITLE
problems whit loading the shader

### ISSUE THREAD

**Issue by theRealLoopDev** [BalintCsala/VanillaPuddingTart#17]
**Description of the bug**
When I try loading the shader, it fails.

**Resourcepack in use**
no one

**System information**
The specs of your computer, example:
GPU: Nvidia GTX 1650
CPU: Intel(R) Core(TM) i5-10400F
OS: Windows 11

**Screenshots**
(Optional)
![image](https://user-images.githubusercontent.com/88555889/211813372-7e86ee45-fc58-417f-a3bc-175bfaa5426e.png)

**Attach the logs**
[latest.log](https://github.com/BalintCsala/VanillaPuddingTart/files/10392599/latest.log)

**Comment by BalintCsala** [comment]
Did you follow the installation instructions outlined in every release post? You have to use a resourcepack for instance for this to work

**Comment by theRealLoopDev** [comment]
Thanks, I didn't read that well enough

**Comment by theRealLoopDev** [comment]
now that I have installed the pack and played around with, I have noticed that in surfaces that reflects light like iron, your skin wasn't mirrorred (left side of your skin is still left, not right like real life)

**Comment by BalintCsala** [comment]
Will be fixed in the next version
