### ISSUE TITLE
Unable to load ressource pack - 1.2.0 version

### ISSUE THREAD

**Issue by SpidFightFR** [BalintCsala/VanillaPuddingTart#19]
**Description of the bug**
- When I try loading the shader, with fabulous mode on, it fails: it sets back everything on default.

**Resourcepack in use**
Vanilla normals renewed.

**System information**
The specs of your computer, example:
GPU: AMD RX 7900 XTX
CPU: AMD Ryzen 2600
OS: Linux

**Screenshots**
N.A

**Attach the logs**
Here are the [logs](https://mclo.gs/BCuyxW7).

**Comment by BalintCsala** [comment]
I updated the zip file in the patreon post, please redownload it

**Comment by SpidFightFR** [comment]
indeed, it's solved, thank you !
