### ISSUE TITLE
Visual artifacts while looking at lava

### ISSUE THREAD

**Issue by SpidFightFR** [BalintCsala/VanillaPuddingTart#20]
**Description of the bug**
Hey, it's me again !
- When i try to look at lava, it makes weird glitches with missing textures like on gmod (check screenshots).

**Resourcepack in use**
VNR

**System information**
GPU: AMD RX 7900 XTX
CPU: AMD Ryzen 2600
OS: Linux

**Screenshots**
[link](https://i.imgur.com/xCjpcUr.jpg) [link2](https://i.imgur.com/oqUut1E.jpg)

**Attach the logs**
You can find the logs right [there](https://mclo.gs/0lHdFrq).

**Comment by BalintCsala** [comment]
That's an issue with VNR, think they are doing something weird with models I don't support properly. I'll see if I can fix that by the next release

**Comment by SpidFightFR** [comment]
Understood, in the meantime i’ll try with another ressource pack.

By the way, does VPT work with any labPBR RP or it only works with those specified in your wiki?
I tried to convert the [Vanilla-labPBR](https://www.curseforge.com/minecraft/texture-packs/vanilla-pbr) ressource pack using your website but, unlike for VNR, it’s remains stuck at the last step of conversion (something related to models), i’m not sure why…

**Comment by BalintCsala** [comment]
Mostly fixed in 1.3.0
