### ISSUE TITLE
The segment that emit light was offset differently when torch was placed on wall

### ISSUE THREAD

**Issue by somkidlove2** [BalintCsala/VanillaPuddingTart#23]
![2023-04-13_18 26 00](https://user-images.githubusercontent.com/130661543/231744607-6d6e6601-7a3d-43a8-9668-bfb599d2d539.png)

System infomation
CPU: AMD Ryzen 5 3600
GPU: Radeon RX 570 Series
OS: Windows 11

**Comment by BalintCsala** [comment]
This is a known issue
![image](https://user-images.githubusercontent.com/33815391/231749129-c0090959-f67d-469f-9da5-38d6ff91c7a2.png)

**Comment by BalintCsala** [comment]
Fixed in 1.3.0
