### ISSUE TITLE
The player shadow loosely follow the player when switched to 3rd person mode

### ISSUE THREAD

**Issue by somkidlove2** [BalintCsala/VanillaPuddingTart#25]
**System information**
The specs of your computer, example:
GPU: Nvidia RTX 3070
CPU: AMD Ryzen 5400
OS: Windows 11

**Video**
https://user-images.githubusercontent.com/130661543/232688546-abdc2ef6-dd02-489e-af5a-3630a4e04a8e.mp4

**Comment by BalintCsala** [comment]
The player shadow is just faked according to the camera position, since the shader doesn't get any info about the entities. Won't fix
