### ISSUE TITLE
Extremely Low Framerate When Maximized

### ISSUE THREAD

**Issue by 4194304** [BalintCsala/VanillaPuddingTart#28]
**Description of the bug**
In the normal game resolution, the game works perfectly fine, and it sits at a stable 50 fps. When maximizing the window, the game drops all the way down to around 8 fps average. There is another rendering issue that occurs when at the normal game resolution but I would rather leave that as its own bug report independent from this

**Resourcepack in use**
VanillaPuddingTart, absolutely nothing else

**System information**
The specs of your computer, example:
GPU: Nvidia GTX 1050 Ti
CPU: Intel i9-9900K @5GHz
OS: Windows 11

**Screenshots**
![2023-07-07_20 02 29](https://github.com/BalintCsala/VanillaPuddingTart/assets/130800536/572aec51-b89f-4a8a-a35c-25d9bda3ea9e)
854x480, default resolution

![2023-07-07_20 02 34](https://github.com/BalintCsala/VanillaPuddingTart/assets/130800536/e012e80d-9333-43ea-aff9-0e422246c38b)
Maximized, extremely low framerate

**Attach the logs**
No relevant logs

Optimally you should follow these steps:
1. Load the shader
2. Maximize your game window

**Comment by BalintCsala** [comment]
That performance is about what I would expect, you're running the game at 5x the pixels after all
