### ISSUE TITLE
White Boxes Appear When Moving

### ISSUE THREAD

**Issue by 4194304** [BalintCsala/VanillaPuddingTart#29]
**Description of the bug**
When moving at the game's normal window resolution, white squares randomly appear and disappear on different blocks.

**Resourcepack in use**
None

**System information**
The specs of your computer, example:
GPU: Nvidia GTX 1050 Ti
CPU: i9-9900K@5GHz
OS: Windows 11

**Screenshots**
This can't be properly shown without video, however screenshots will be linked
![2023-07-07_20 02 34](https://github.com/BalintCsala/VanillaPuddingTart/assets/130800536/462f4d2d-d990-414c-8c17-f7a29fee9a4d)
White boxes when moving

https://github.com/BalintCsala/VanillaPuddingTart/assets/130800536/91c474e9-4987-48c8-8ae0-a2a7e7b1f28e
White boxes on video

**Attach the logs**
N/A

Optimally you should follow these steps:
1. Set the game to 854x480
2. Move and see white boxes appear

**Comment by BalintCsala** [comment]
Minimum resolution is 1024x768, I'll add this in the modrinth description later, but it's not something I'll fix
